# Generated by Django 4.0.4 on 2022-05-29 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ingredient_recipe_ingredredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredredients',
            new_name='ingredients',
        ),
    ]
